version: "3.7"

services:
  web1:
    build:
      context: ./quote_gen
    ports:
      - "5000-5002:5000"
    volumes:
      - ./quote_gen:/app
    deploy:
      replicas: 2
  

  web2:
    build:
      context: ./quote_disp
    ports:
      - "5003-5006:5001"
    depends_on:
      - web1
    volumes:
      - ./quote_disp:/app
    deploy:
      replicas: 2
 
