name: test_quote_disp

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install -r ./quote_disp/requirements.txt
      - name: Set PYTHONPATH
        run: |
          export PYTHONPATH=/workspaces/devops-cc-week-2
      - name: Run tests
        run: |
          pytest tests/*disp* --junitxml=pytest_quote_disp.xml --cov-report=term-missing:skip-covered --cov=app tests/ | tee pytest_quote_disp_coverage.txt
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest_quote_disp_coverage.txt
          junitxml-path: ./pytest_quote_disp.xml